### ISSUE TITLE
jQuery failing to load

### ISSUE THREAD

**Issue by caleyshemc** [stephenmcd/mezzanine.jupo.org#9]
I noticed that jQuery fails to load when I attempted to add images to a new product. The popup window shows up, but nothing happens when I click the button to send the image to the product creation page.

I saw the following error on every page in the admin section of the site:
http://mezzanine.jupo.org/static/mezzanine/js/jquery-1.8.3.min.js Failed to load resource: the server responded with a status of 404 (Not Found)

With of course several instances of:
Uncaught ReferenceError: jQuery is not defined

**Comment by stephenmcd** [comment]
Loading now, thanks.
